// This file should look something like this:

// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

//#include "pico sdk path/pico-sdk/src/boards/include/boards/pico_w.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:

//#include "pico sdk path/pico-sdk/src/rp2_common/cmsis/include/cmsis/rename_exceptions.h"